version: "3"
services:
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 89f8sdf9fs9
      MYSQL_DATABASE: fullstack
      MYSQL_USER: fullstacker
      MYSQL_PASSWORD: fd9jmmfds8
    container_name: mysql
  backend:
    image: studentsystem:0.0.1-SNAPSHOT
    restart: on-failure
    depends_on:
      - db
    container_name: backend
  frontend:
    build: ./frontend
    depends_on:
      - backend
    container_name: studentsystem
  nginx:
    build: ./nginx
    ports:
      - "80:80"
    ports:
      - "8080:8080"
    container_name: nginx
    depends_on:
      - backend
      - frontend

